### PR TITLE
Fix missing required parameter in RunController:274

### LINKED ISSUE #471: Missing required parameter in RunController:274
When trying to compare runs the following error comes up.

```
"Message: Too few arguments to function XHGui\RequestProxy::get(), 0 passed in /var/www/xhgui/src/Controller/RunController.php on line 274 and at least 1 expected"
```
https://github.com/perftools/xhgui/blob/448c6d722440171612f9a257dcd6912fc940aae8/src/Controller/RunController.php#L274

### PR DESCRIPTION
**Pull request by sunanzhi**
when I access `/run/compare?base=xxx` page, Pagination is unavailable because of this bug.
because `templates/runs/compare.twig`  referencing a nonexistent value -> `{{ helpers.pagination('run.compare', pagination, url_params) }}`

fixes https://github.com/perftools/xhgui/issues/471

### CODE REVIEW

File: src/Controller/RunController.php [hunk 1]
```diff
@@ -271,9 +271,11 @@ public function compare(Request $request): void
             'base_run' => $baseRun,
             'head_run' => $headRun,
             'candidates' => $candidates,
-            'url_params' => $request->get(),
+            // 'url_params' => $request->get(),
```
Comment (glensc) [inline src/Controller/RunController.php]: why is this commented out? remove dead code.

File: src/Controller/RunController.php [hunk 2]
```diff
@@ -271,9 +271,11 @@ public function compare(Request $request): void
...
+            'url_params' => $request->getQueryParams(),
             'comparison' => $comparison,
             'paging' => $paging,
+            'pagination' => $paging,
```
Comment (glensc) [inline src/Controller/RunController.php]: why is the `pagination` key added?

File: src/Controller/RunController.php (hunk 1 above)
Comment (sunanzhi) [reply src/Controller/RunController.php]: ok i will re-pr

File: src/Controller/RunController.php (hunk 2 above)
Comment (sunanzhi) [reply src/Controller/RunController.php]: compare.twig referencing a nonexistent value -> {{ helpers.pagination('run.compare', pagination, url_params) }} 
 i will remove old key `paging`.

Comment (sunanzhi) [reply src/Controller/RunController.php]: OR
{{ helpers.pagination('run.compare', pagination, url_params) }}
to
{{ helpers.pagination('run.compare', paging, url_params) }}

File: src/Controller/RunController.php (hunk 1 above)
Comment (glensc) [reply src/Controller/RunController.php]: what? just add more commits!

File: src/Controller/RunController.php (hunk 2 above)
Comment (glensc) [reply src/Controller/RunController.php]: yes, change to use only one value. don't duplicate.

File: src/Controller/RunController.php (hunk 1 above)
Comment (sunanzhi) [reply src/Controller/RunController.php]: sry, im wrong expression, you can check this pr, already 2 commits.

File: src/Controller/RunController.php (hunk 2 above)
Comment (glensc) [reply src/Controller/RunController.php]: other templates still use `paging`, so change to use `paging` in compare.twig as well:
- https://github.com/perftools/xhgui/blob/448c6d722440171612f9a257dcd6912fc940aae8/templates/runs/list.twig#L71

so, do the opposite, revert the changes in code, but fix template.

Comment (glensc) [reply src/Controller/RunController.php]: unresolving, as not done as asked.

**Comment by sunanzhi** [comment]
wait, tomorrow i will fix it and commit again.

NOTE: Edited by maintainer to remove email spam.

File: src/Controller/RunController.php (hunk 2 above)
Comment (sunanzhi) [reply src/Controller/RunController.php]: done
